export const ADICIONA_PROJETO = 'ADICIONA_PROJETO'
export const ALTERA_PROJETO = 'ALTERA_PROJETO'
export const EXCLUIR_PROJETO = 'EXCLUIR_PROJETO'

export const NOTIFICAR = 'NOTIFICAR'

export const GET_PROJETO = 'GET_PROJETO'
export const GET_TAREFAS = 'GET_TAREFAS'
export const ADD_TAREFAS = 'ADD_TAREFAS'